name=DashlyClient
version=2.1.1
author=Smart Stack Solutions
maintainer=Smart Stack Solutions <support@dashlyiot.com>
sentence=Official Arduino client for DashlyIoT.com.
paragraph=A fast and lightweight library to connect your ESP32 or ESP8266 to DashlyIoT dashboards. Send sensor data and receive real-time commands with ease.
category=Communication
url=https://dashlyiot.com
architectures=esp32,esp8266
includes=DashlyClient.h
